### ISSUE TITLE
Availability Information an animes main page hardly readable.

### ISSUE THREAD

**Issue by Cookietogo97** [link07/Dark-Crunchyroll-Plugin#5]
The availability information box that tells you when there are changes in a schedule has a yellowish background color with white text, what makes it hard to read.

Example of the Boruto page.

![wrong color](https://user-images.githubusercontent.com/19735548/39519998-3fc072c4-4e09-11e8-940b-ed7838b772cb.PNG)

**Comment by link07** [comment]
Was a really easy fix.  I've been wanting to fix another small issue (background on the login page), so I'll fix that and get a release posted.

![chrome_2018-05-02_05-11-52](https://user-images.githubusercontent.com/1685504/39520317-643c03bc-4dc7-11e8-9b7b-bf24328f923e.png)
